<?php echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://drink-up-store.epizy.com/</loc>
<lastmod>2020-03-12</lastmod>
<changefreq>weekly</changefreq>
<priority>0.95</priority>
</url>
<url>
<loc>https://drink-up-store.epizy.com/home</loc>
<lastmod>2020-03-12</lastmod>
<changefreq>weekly</changefreq>
<priority>0.9</priority>
</url>
<url>
<loc>https://drink-up-store.epizy.com/store</loc>
<lastmod>2020-03-12</lastmod>
<changefreq>monthly</changefreq>
<priority>0.7</priority>
</url>
<url>
<loc>https://drink-up-store.epizy.com/contacthome</loc>
<lastmod>2020-03-06</lastmod>
<changefreq>weekly</changefreq>
<priority>0.7</priority>
</url>
<url>
<loc>https://drink-up-store.epizy.com/author</loc>
<lastmod>2020-03-12</lastmod>
<changefreq>monthly</changefreq>
<priority>0.65</priority>
</url>
<url>
<loc>https://drink-up-store.epizy.com/cart</loc>
<lastmod>2020-03-12</lastmod>
<changefreq>monthly</changefreq>
<priority>0.65</priority>
</url>
<url>
<loc>https://drink-up-store.epizy.com/loginhome</loc>
<lastmod>2020-03-12</lastmod>
<changefreq>yearly</changefreq>
<priority>0.55</priority>
</url>
<url>
<loc>https://drink-up-store.epizy.com/registerhome</loc>
<lastmod>2020-03-12</lastmod>
<changefreq>yearly</changefreq>
<priority>0.55</priority>
</url>
<url>
<loc>https://drink-up-store.epizy.com/logout</loc>
<lastmod>2020-03-12</lastmod>
<changefreq>yearly</changefreq>
<priority>0.55</priority>
 </url>
</urlset>
